#!/usr/bin/env bash
# Remove plugin state left over from previous plugin managers (packer, lazy.nvim,
# lsp-zero/mason) so `vim.pack` + nvim-treesitter `main` start from a clean slate.
#
# Safe to run repeatedly. Does NOT touch:
#   - ~/.local/share/nvim/site/pack/core  (current vim.pack plugins)
#   - ~/.local/share/nvim/undo            (persistent undo history)
#   - ~/.config/nvim                      (this config)
#
# After running, launch nvim once: vim.pack reinstalls managed plugins and
# nvim-treesitter reinstalls parsers into ~/.local/share/nvim/site/parser.

set -euo pipefail

DATA="${XDG_DATA_HOME:-$HOME/.local/share}/nvim"

echo "Cleaning stale Neovim plugin state under $DATA"

stale=(
  "$DATA/lazy"                     # lazy.nvim tree
  "$DATA/site/pack/packer"         # packer tree
  "$DATA/site/queries"             # symlinked master-branch treesitter queries
  "$DATA/site/parser"              # parsers (regenerated by :TSUpdate on next launch)
  "$DATA/mason"                    # mason.nvim / lsp-zero
  "$DATA/rplugin.vim"              # remote plugin manifest (regenerated)
  "$DATA/telescope_history"        # telescope (no longer used)
)

for path in "${stale[@]}"; do
  if [ -e "$path" ] || [ -L "$path" ]; then
    echo "  rm -rf $path"
    rm -rf "$path"
  fi
done

# Clear stray lock files that block `vim.pack.update()`.
find "$DATA/site/pack" -name index.lock -delete 2>/dev/null || true

echo "Done. Start nvim to reinstall plugins and parsers, then run :TSUpdate."
